apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      proxyMetadata:
        # Enable basic DNS proxying
        ISTIO_META_DNS_CAPTURE: "true"
        # Enable automatic address allocation, optional
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
    accessLogFile: /dev/stdout

  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
    - name: istio-egressgateway
      enabled: false
    - name: istio-eastwestgateway
      label:
        istio: eastwestgateway
        app: istio-eastwestgateway
        topology.istio.io/network: network2
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
        env:
          # traffic through this gateway should be routed inside the network
          - name: ISTIO_META_REQUESTED_NETWORK_VIEW
            value: network2
        service:
          type: NodePort
          ports:
            - name: status-port
              port: 15021
              targetPort: 15021
              nodePort: 30070
            - name: tls
              port: 15443
              targetPort: 15443
              nodePort: 30071
            - name: tls-istiod
              port: 15012
              targetPort: 15012
              nodePort: 30072
            - name: tls-webhook
              port: 15017
              targetPort: 15017
              nodePort: 30073

    pilot:
      k8s:
        env:
          - name: PILOT_TRACE_SAMPLING
            value: "1"
        resources:
          requests:
            cpu: 10m
            memory: 100Mi

  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster2
      network: network2
      proxy:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
      meshNetworks:
        network1:
          endpoints:
            - fromRegistry: cluster1
          gateways:
            - address: 10.239.235.81 #cluster1 nodeIP
              port: 30071 #eastwest gw nodeport
            - address: 10.239.245.37 #cluster1 nodeIP
              port: 30071 ##eastwest gw nodeport

    pilot:
      autoscaleEnabled: false

    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
      istio-ingressgateway:
        autoscaleEnabled: false